### ISSUE TITLE
很实用的工具。如何设定下载目标目录

### ISSUE THREAD

**Issue by yuritry** [Mrs4s/six-cli#1]
rt

**Comment by yuritry** [comment]
下载目录，如果文件过多，会报错。

**Comment by Mrs4s** [comment]
可以在Config.json设置下载目录，下个更新会加上相关命令的。
请问具体是什么错误，最好能上图。

**Comment by yuritry** [comment]
下载错误：

4.zip 9.50 GiB / 10.20 GiB [============================>--]  92.38% 7.85 MiB/s 01m30spanic: runtime error: index out of range [0] with length 0

goroutine 13817 [running]:
github.com/Mrs4s/go-http-downloader.(*DownloaderClient).BeginDownload.func1.1(0xc002802a20, 0xc0004cc360)
        /Users/sijiang/go/pkg/mod/github.com/!mrs4s/go-http-downloader@v0.0.0-20191014103207-7f76db391012/downloader.go:84 +0x1ae
created by github.com/Mrs4s/go-http-downloader.(*DownloaderClient).BeginDownload.func1
        /Users/sijiang/go/pkg/mod/github.com/!mrs4s/go-http-downloader@v0.0.0-20191014103207-7f76db391012/downloader.go:64 +0x246

**Comment by yuritry** [comment]
目录下文件多，添加失败：

[+] 添加下载阎连科的中篇小说《为人民服务》.pdf
error to handle command Download : runtime error: invalid memory address or nil pointer dereference

**Comment by yuritry** [comment]
下载无法终止？

**Comment by yuritry** [comment]
文件下载到一半，系统停滞，毫无反应

**Comment by Mrs4s** [comment]
找到问题了，下个版本会修复

**Comment by yuritry** [comment]
断点传续，不下载重复文件，下载文件检查，可能这些功能也需要。
谢谢。

**Comment by Mrs4s** [comment]
等适配完v3会更新这些功能的。

**Comment by chuchenting** [comment]
有辦法透過CLI獲取http開頭的下載路徑嗎?
